#!/bin/sh

# (C) Copyright 2010 Marek Dopiera
# 
# This file is part of CherentDB.
# 
# CoherentDB is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# CoherentDB is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with Foobar. If not, see
# http://www.gnu.org/licenses/.

set -e
rm -f ${DUMPFILE}
DUMPFILE="$1"
shift
(
echo "#ifndef COMPILE_H_2492"
echo "#define COMPILE_H_2492"
echo "/* This file is autogenerated - do not change */"
echo ""
echo "#define COMPILED_CXXFLAGS \"$1\""
shift
echo "#define COMPILED_CFLAGS \"$1\""
echo ""
echo "#endif /* COMPILE_H_2492 */"
) > "${DUMPFILE}"
