#!/bin/sh

# (C) Copyright 2010 Marek Dopiera
#
# This file is part of CoherentDB.
# 
# CoherentDB is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# CoherentDB is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with CoherentDB. If not, see
# http://www.gnu.org/licenses/.

set -e

PROJ_DIR=`dirname $0`/..
cd "$PROJ_DIR"

if [ -d  ".git" ] ; then
	GIT_DIR_PRESENT=YES
else
	GIT_DIR_PRESENT=NO
fi

if git help 1>/dev/null 2>/dev/null ; then
	GIT_PRESENT=YES
else
	GIT_PRESENT=NO
fi

if [ -f src/include/release.h ] ; then
	OFFICIAL_RELEASE=YES
else
	OFFICIAL_RELEASE=NO
fi

if [ $GIT_DIR_PRESENT = "YES" -a $GIT_PRESENT = "YES" ] ; then
	ON_BRANCH=YES
	GIT_BRANCH=`git branch | head -1 | cut -c3-`
	if [ "${GIT_BRANCH}" = "(no branch)" ] ;then
		ON_BRANCH=NO
	fi

	if [ `git status -s | grep -v "^??" | wc -l` -ne 0 ] ; then
		MODIFIED=YES
	else
		MODIFIED=NO
	fi

	HASH=`git log "--pretty=format:%H" | head -1`
fi

DATE=`date "+%y/%m/%d %H:%M:%S"`
OS=`uname -s`
ARCH=`uname -m`
UNAME=`uname -a`

(
echo "#ifndef VERSION_H_5373"
echo "#define VERSION_H_5373"
echo ""
echo "/* This file is autogenerated - do not change*/"
echo ""
echo ""
echo "#define BUILD_TIME \"${DATE}\"" 
echo "#define BUILD_OS \"${OS}\""
echo "#define BUILD_ARCH \"${ARCH}\""
echo "#define FULL_UNAME \"${UNAME}\""
if [ $OFFICIAL_RELEASE = "YES" ] ; then
	echo "#define OFFICIAL_RELEASE \"`cat src/include/release.h`\""
fi
if [ $GIT_PRESENT = YES -a $GIT_DIR_PRESENT = YES ] ; then
	if [ ${MODIFIED} = NO ] ; then
		echo "#define GIT_HASH \"${HASH}\""
	else
		echo "#define GIT_HASH \"${HASH} (modified)\""
	fi
	if [ ${ON_BRANCH} = "YES" ] ; then
		echo "#define GIT_BRANCH \"${GIT_BRANCH}\""
	fi
fi
echo ""
echo ""
echo "#endif /* VERSION_H_5373 */"
) > "$1"
